# Generated by Django 5.2.1 on 2025-05-21 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(verbose_name="Event date and time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=250, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizer",
            ),
        ),
    ]
